### PR TITLE
Added scenarios from Karyn and cleaned up seed data

### PR DESCRIPTION
**Pull request by mischa-s**
Have done a major clean up of the seed data with the criteria that each result should present some unique case for what we are building

Questions which emerged from this are:

- Should we add `DOB` to the identities table?
- Should we add `Destination to / from` to the movements table?

> Travel to one of the countries counted as NZ (Cook Islands, Niue, Tokelau & Antarctica). *Hazel says: There are rules that come from Legislation that can be automated. This is the Rules part of the engine model. **This is the first piece of work to be done on the project**

- Is ⇧ a thing we need to build ? 
- What is a serial number? What is an identity number? 

part of #221

### CODE REVIEW

**Comment by Br3nda** [comment]
These are good - let's merge - but it does not close #221 until these are turned into tests, not just Factory bots.

**Comment by Br3nda** [comment]
Re the cook island and other islands and former territories of NZ, Kirsty said not for alpha.

**Comment by mischa-s** [comment]
Okay cool. Very true about the tests, will do that now

**Comment by Br3nda** [comment]
Cool! Up to you if you write tests on this PR, or on a second one.

**Pull request merged**
